---
- name: Install certbot
  package:
    name: certbot
    state: present

- name: Ensure certbot timer enabled (systemd)
  systemd:
    name: certbot-renew.timer
    enabled: true
    state: started
