---
- name: Single host all-in-one
  hosts: all
  become: true

  tasks:
    - name: Configure sysctl
      include_tasks: tasks/sysctl.yml
      tags: sysctl

    - name: Configure users
      include_tasks: tasks/users.yml
      tags: users

    - name: Certbot
      include_tasks: tasks/certbot.yml
      tags: certbot

    - name: Work with files and dirs
      import_tasks: tasks/files.yml
      tags: files

  handlers:
    - name: Reload sysctl
      command: sysctl --system
